services:

  #db-urls:
  #  image: mongo
  #  restart: always
  #  ports:
  #    - 27017:27017
  #  container_name: db-urls

  db-short-urls:
    image: mongo
    restart: always
    ports:
      - 5432:27017
    container_name: db-short-urls
